name: Flutext CI

on:
  push:
    branches:
    - master
    - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        java-version: '17.0'
        distribution: 'microsoft'
    
    # setup flutter env
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.0.5'
        channel: 'stable'
    
    - run: flutter pub get
    
    - run: flutter format --set-exit-if-changed
    
    - run: flutter analyse
    
    - run: flutter test
    
    - run: flutter build apk
    
    # Upload generated apk to the artifacts
    # - uses: actions/upload-artifact@v3
    #  with:
    #    name: release-apk
    #    path: build/app/outputs/apk/release/app-release.apk
        
